"""parse_ddl — Oracle SQL*Plus script handling: directive stripping, ALTER TABLE
constraint extraction, and the string/comment scanner that guards both."""

from __future__ import annotations

from breezeai_cog.analyzers.sql import _strip_sqlplus, parse_ddl

# A trimmed Oracle SQL*Plus script in the shape of a real schema install script:
# rem/Prompt/SET directives between statements, a multi-line COMMENT string, and all
# PK/FK/UNIQUE constraints declared via ALTER TABLE rather than inline.
ORACLE_SQLPLUS = """rem
rem Copyright (c) 2023
rem
SET FEEDBACK 1
SET LINESIZE 80

Prompt ******  Creating CUSTOMERS table ....

CREATE TABLE customers
(
  customer_id     INTEGER GENERATED BY DEFAULT ON NULL AS IDENTITY,
  email_address   VARCHAR2(255 CHAR) NOT NULL,
  full_name       VARCHAR2(255 CHAR) NOT NULL
);

Prompt ******  Creating ORDERS table ....

CREATE TABLE orders
(
  order_id       INTEGER GENERATED BY DEFAULT ON NULL AS IDENTITY,
  customer_id    INTEGER NOT NULL,
  order_status   VARCHAR2(10 CHAR) NOT NULL
);

Prompt ******  Creating a view

CREATE OR REPLACE VIEW customer_orders AS
  SELECT c.customer_id, o.order_id
  FROM   customers c JOIN orders o ON c.customer_id = o.customer_id;

Prompt ******  Creating indexes ...

CREATE INDEX orders_customer_id_i ON orders ( customer_id );

Prompt ******  Adding constraints ...

ALTER TABLE customers ADD CONSTRAINT customers_pk PRIMARY KEY (customer_id);
ALTER TABLE customers ADD CONSTRAINT customers_email_u UNIQUE (email_address);
ALTER TABLE orders ADD CONSTRAINT orders_pk PRIMARY KEY (order_id);
ALTER TABLE orders ADD CONSTRAINT orders_customer_id_fk
   FOREIGN KEY (customer_id) REFERENCES customers (customer_id);

Prompt ******  Comments ...

COMMENT ON COLUMN orders.order_status
  IS 'What state the order is in. Valid values are:
OPEN - the order is in progress
COMPLETE - the customer has received the order';
"""


def _by_name(records: list[dict]) -> dict[str, dict]:
    return {r["name"]: r for r in records}


def test_sqlplus_directives_do_not_block_parsing() -> None:
    r = parse_ddl(ORACLE_SQLPLUS, "co_create.sql")
    # Without directive stripping every table/view fails to parse (rem/Prompt glue
    # onto the following CREATE); the whole file should now parse cleanly.
    assert r["dialect"] == "oracle"
    assert r["parseStats"]["failed"] == 0
    assert {t["name"] for t in r["tables"]} == {"customers", "orders"}
    assert {v["name"] for v in r["views"]} == {"customer_orders"}
    assert len(r["allIndexes"]) == 1


def test_alter_table_constraints_are_captured() -> None:
    r = parse_ddl(ORACLE_SQLPLUS, "co_create.sql")
    tables = _by_name(r["tables"])

    # PK declared via ALTER TABLE must set hasPrimaryKey + the column flag.
    customers = tables["customers"]
    assert customers["hasPrimaryKey"] is True
    assert _by_name(customers["columns"])["customer_id"]["isPrimaryKey"] is True

    # FK declared via ALTER TABLE must be captured with ref table/columns + column flag.
    orders = tables["orders"]
    fks = [c for c in orders["constraints"] if c["constraintType"] == "FOREIGN_KEY"]
    assert len(fks) == 1
    assert fks[0]["refTableName"] == "customers" and fks[0]["refColumns"] == ["customer_id"]
    assert _by_name(orders["columns"])["customer_id"]["isForeignKey"] is True

    # UNIQUE via ALTER TABLE captured as a constraint.
    uniques = [c["columns"] for c in customers["constraints"] if c["constraintType"] == "UNIQUE"]
    assert uniques == [["email_address"]]

    # Index ownership + isIndexed wiring still works alongside ALTER constraints.
    assert _by_name(orders["columns"])["customer_id"]["isIndexed"] is True


def test_index_only_ownership() -> None:
    r = parse_ddl(ORACLE_SQLPLUS, "co_create.sql")
    orders = _by_name(r["tables"])["orders"]
    assert [i["name"] for i in orders["indexes"]] == ["orders_customer_id_i"]


def test_multiline_string_survives_stripping() -> None:
    # A directive-looking line ("COMPLETE - ...") inside a multi-line COMMENT string
    # must not be dropped, and its content must remain intact.
    cleaned = _strip_sqlplus(ORACLE_SQLPLUS)
    assert "OPEN - the order is in progress" in cleaned
    assert "COMPLETE - the customer has received the order" in cleaned


def test_line_comment_apostrophe_does_not_flip_string_state() -> None:
    # A '--' comment containing an apostrophe must not be treated as an open string,
    # which would otherwise swallow the following SET directive / CREATE.
    text = "-- Bob's schema\nSET FEEDBACK 1\nCREATE TABLE t (id INTEGER);\n"
    cleaned = _strip_sqlplus(text)
    assert "SET FEEDBACK 1" not in cleaned
    assert "CREATE TABLE t" in cleaned
    r = parse_ddl(text, "t_ora.sql")
    assert [t["name"] for t in r["tables"]] == ["t"]


def test_block_comment_body_preserved() -> None:
    text = "/* rem\nprompt\n*/\nCREATE TABLE z (id INTEGER);\n"
    cleaned = _strip_sqlplus(text)
    # The 'rem'/'prompt' lines live inside a block comment and must be kept.
    assert "rem" in cleaned and "prompt" in cleaned
    assert "CREATE TABLE z" in cleaned


def test_bare_slash_terminator_dropped() -> None:
    text = "CREATE TABLE t (id INTEGER)\n/\n"
    cleaned = _strip_sqlplus(text)
    assert "\n/" not in cleaned and not cleaned.strip().endswith("/")
